# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [pull_request]

jobs:
  # install dependencies and store artifact
  package:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      # 1: Setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      # 2: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 3: Install dependencies
      - name: Install dependencies
        run: yarn --frozen-lockfile
      
      # 5: Build package
      - name: Build Package
        run: yarn build

      # 6: Store artifact
      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: |
            dist
            manifest.json
  # install dependencies and run test command
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      # 1: Setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      # 2: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 3: Install dependencies
      - name: Install dependencies
        run: yarn --frozen-lockfile
      
      # 4: Run tests
      - name: Run test command
        run: yarn test
      
      # 5: Run test coverage report
      - name: Run test coverage report
        id: testCoverage
        uses: anuraag016/Jest-Coverage-Diff@master
        with:
          fullCoverageDiff: false
          runCommand: "npx jest --collectCoverageFrom='[\"src/**/*.{js,jsx,ts,tsx}\"]' --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary' --forceExit --detectOpenHandles"
          delta: 0.5
  test-transform:
    name: Transformer Tests
    runs-on: ubuntu-latest
    steps:
      # 1: Setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      # 2: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 3: Install dependencies
      - name: Install dependencies
        run: yarn --frozen-lockfile

      # 4: Build package
      - name: Build Package
        run: yarn build-transform

      # 5: Install dependencies
      - name: Install dependencies
        run: cd token-transformer && yarn --frozen-lockfile
      
      # 6: Run tests
      - name: Run test command
        run: cd token-transformer && yarn test
  cypress-run:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      # 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v2
      # 2: Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build:cy
          start: yarn serve
